# Generated by Django 5.2.2 on 2025-06-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=50)),
                ('set_name', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=50)),
                ('price_charting_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
