# Generated by Django 5.2.2 on 2025-06-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boosterpack',
            name='release_date',
            field=models.DateField(max_length=50),
        ),
    ]
