# Generated by Django 5.2.2 on 2025-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_alter_boosterpack_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boosterpack',
            options={},
        ),
        migrations.AddField(
            model_name='boosterpack',
            name='high_price',
            field=models.IntegerField(blank=True, help_text='Higher end of the price range (for sorting)', null=True),
        ),
        migrations.AddField(
            model_name='boosterpack',
            name='low_price',
            field=models.IntegerField(blank=True, help_text='Lower end of the price range (for sorting)', null=True),
        ),
        migrations.AlterField(
            model_name='boosterpack',
            name='price_charting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boosterpack',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boosterpack',
            name='release_date',
            field=models.DateField(),
        ),
    ]
