# Generated by Django 5.2.2 on 2025-06-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_alter_boosterpack_options_boosterpack_high_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boosterpack',
            name='price_range',
            field=models.FloatField(default=0.0),
        ),
    ]
