# Generated by Django 5.2.2 on 2025-06-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_alter_boosterpack_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosterpack',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='boosterpack',
            name='low_price',
        ),
    ]
